services:
  flaskapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./certs:/app/certs  # Mount SSL certs if you want them inside
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    command: >
      gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:8000 run:app 
      --keyfile /app/certs/key.pem 
      --certfile /app/certs/cert.pem
